### ISSUE TITLE
Smoothing errors (?) when comparing render with original BRIGL version.

### ISSUE THREAD

**Issue by HerrQ** [HazenBabcock/brigl#1] opened 2016-12-30 22:44 UTC
Please compare the following detail views from rendering the Viper model with 1) the original BRIGL library vs. 2) the modified 'HazenBabcock' BRIGL library. Maybe this is a smoothing issue?

1) Original rendering:
![original](https://cloud.githubusercontent.com/assets/16548989/21573769/ce33e528-cee8-11e6-84c8-389128d1ab29.png)

2) Babcock rendering:
![babcock](https://cloud.githubusercontent.com/assets/16548989/21573773/d870fa80-cee8-11e6-9f5e-920a9b2a41f8.png)

**Comment by HazenBabcock** [comment] 2017-01-01 14:34
Yes it certainly looks like a smoothing issue.

**Comment by HazenBabcock** [comment] 2017-01-17 18:54
The short answer is that I think this going to be very hard to fix properly.

The long answer (oBRIGL = original BRIGL, hBRIGL = 'hbabcock' BRIGHL). The rendering you provided was created using oBRIGL's "original" smoothing algorithm. This is not the smoothing algorithm that is in the most current version of the oBRIGL library from which hBRIGL started. I believe that the "new" smoothing algorithm in oBRIGL was designed to solve the problem where you had a single vertex that was shared by more than two faces all of which also had conditional lines that terminated at the vertex. Unfortunately the new algorithm does not correctly handle the case where a mixture of conditional and non-conditional lines terminate at a vertex. In this case all the face normals associated with the vertex will end up pointing in the same direction, when the right thing would have been for only sub-groups of them to be pointing in the same direction. This is why in the hBRIGL rendering you provided the edges of the small pits appear to be rounded. The conditional lines to smooth the inside of the pit meet the conditional lines to smooth the other curved surfaces of the part at the pit edges. You would also see this if you used the current version of oBRIGL instead of the version at www.lugato.net. The problematic part is #44675.dat and probably the easiest way to see what it actually should look like when smoothed correctly is to load it with LDView.

This is not to say that I did not introduce bugs in the process of changing oBRIGHL to only use triangles and not quads.

And thank you for reporting this. I'll see if I can come up with a fix, but it will likely take some time.

**Comment by HazenBabcock** [comment] 2018-02-17 21:51
This should be fixed now.

**Comment by HazenBabcock** [comment] 2018-02-19 23:04
Closing this for now.

**Closed by HazenBabcock** 2018-02-19 23:04 UTC

**Comment by HazenBabcock** [comment] 2018-02-20 21:48
Hm, already found and fixed one bug.
